{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h1><center>Exception handling-2</center></h1>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Note: Here Exception class refers to the base class for all the exceptions.</h3>\n",
    "<p><b>Answer.</b></p>\n",
    " <h3>Custom Exception with Exception Class</h3>\n",
    "    \n",
    "<p>\n",
    "        In Python, the <code>Exception</code> class is the base class for all exceptions. When creating a custom exception, it is advisable to inherit from the <code>Exception</code> class (or one of its subclasses) to ensure that the custom exception follows the standard conventions and behaviors expected from an exception in the Python language.\n",
    "    </p>\n",
    "\n",
    "<h3>Reasons to Use the Exception Class:</h3>\n",
    "\n",
    "<ol>\n",
    "        <li>\n",
    "            <strong>Consistency and Compatibility:</strong> Inheriting from the <code>Exception</code> class ensures that the custom exception is consistent with the standard exceptions provided by Python. It ensures compatibility with the broader exception-handling infrastructure in Python, making it easier to integrate custom exceptions into existing code and frameworks.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Standard Behaviors:</strong> By inheriting from <code>Exception</code>, the custom exception inherits standard behaviors and attributes common to all exceptions in Python. This includes the ability to carry an optional error message, traceback information, and other attributes that facilitate consistent error handling.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Interchangeability:</strong> Custom exceptions that inherit from <code>Exception</code> can be used interchangeably with built-in exceptions in except clauses, making it easy to catch specific types of exceptions in a unified manner.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Clarity and Readability:</strong> Following the convention of inheriting from the <code>Exception</code> class improves code clarity and readability. Developers reading the code can quickly recognize that a class is intended to be an exception, and they can leverage their existing knowledge of exception handling in Python.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Future-Proofing:</strong> Inheriting from <code>Exception</code> future-proofs the custom exception by ensuring compatibility with any changes or enhancements to the exception-handling system in future Python releases.\n",
    "        </li>\n",
    "    </ol>\n",
    "\n",
    "<h3>Example:</h3>\n",
    "\n",
    "<pre>\n",
    "        <code>\n",
    "class CustomError(Exception):\n",
    "    def __init__(self, message):\n",
    "        super().__init__(message)\n",
    "\n",
    "# Using the custom exception\n",
    "try:\n",
    "    raise CustomError(\"This is a custom exception.\")\n",
    "except CustomError as e:\n",
    "    print(f\"Caught CustomError: {e}\")\n",
    "        </code>\n",
    "    </pre>\n",
    "\n",
    "<p>\n",
    "        In this example, <code>CustomError</code> is a custom exception that inherits from <code>Exception</code>. When raised and caught, it behaves like any other exception in the Python language.\n",
    "    </p>\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"Q2. Write a python program to print Python Exception Hierarchy.\"\"\"\n",
    "\n",
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(\"  \" * indent + f\"{exception_class.__name__}\")\n",
    "    for base_class in exception_class.__bases__:\n",
    "        print_exception_hierarchy(base_class, indent + 1)\n",
    "\n",
    "# Print Python Exception Hierarchy\n",
    "print(\"Python Exception Hierarchy:\")\n",
    "print_exception_hierarchy(BaseException)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.</h3>\n",
    "<p><b>Answer.</b></p>\n",
    "\n",
    "<h3>Arithmetic Errors in Python</h3>\n",
    "    \n",
    "<p>\n",
    "        The <code>ArithmeticError</code> class in Python is the base class for exceptions that occur during arithmetic operations. Two common errors derived from <code>ArithmeticError</code> are <code>ZeroDivisionError</code> and <code>OverflowError</code>.\n",
    "    </p>\n",
    "\n",
    "<h3>1. ZeroDivisionError:</h3>\n",
    "\n",
    "<p>\n",
    "        The <code>ZeroDivisionError</code> is raised when attempting to divide a number by zero. It represents an arithmetic operation where the denominator is zero.\n",
    "    </p>\n",
    "\n",
    " <pre>\n",
    "        <code>\n",
    "try:\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "        </code>\n",
    "    </pre>\n",
    "\n",
    "<p>\n",
    "        In this example, attempting to divide 10 by 0 will result in a <code>ZeroDivisionError</code>, and the program will print an error message.\n",
    "    </p>\n",
    "\n",
    "<h3>2. OverflowError:</h3>\n",
    "\n",
    "<p>\n",
    "        The <code>OverflowError</code> is raised when the result of an arithmetic operation exceeds the representational limits of the data type.\n",
    "    </p>\n",
    "\n",
    "<pre>\n",
    "        <code>\n",
    "try:\n",
    "    result = 2 ** 1000  # Exponential operation leading to overflow\n",
    "except OverflowError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "        </code>\n",
    "    </pre>\n",
    "\n",
    "<p>\n",
    "        In this example, attempting to calculate 2 to the power of 1000 using the exponential operator will result in an <code>OverflowError</code>, as the result is too large to be represented.\n",
    "    </p>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.</h3>\n",
    "\n",
    "<p><b>Answer.</b></p>\n",
    "<h3>LookupError Class in Python</h3>\n",
    "    \n",
    "<p>\n",
    "        The <code>LookupError</code> class in Python is the base class for exceptions that occur when a key or index is not found during a lookup operation. Two common errors derived from <code>LookupError</code> are <code>KeyError</code> and <code>IndexError</code>.\n",
    "    </p>\n",
    "\n",
    "<table border=\"1\">\n",
    "        <tr>\n",
    "            <th>Error Class</th>\n",
    "            <th>Description</th>\n",
    "            <th>Example</th>\n",
    "        </tr>\n",
    "        <tr>\n",
    "            <td><code>KeyError</code></td>\n",
    "            <td>Occurs when trying to access a key that is not present in a dictionary.</td>\n",
    "            <td>\n",
    "                <pre><code>\n",
    "try:\n",
    "    my_dict = {'a': 1, 'b': 2}\n",
    "    value = my_dict['c']  # Accessing a non-existent key\n",
    "except KeyError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "                </code></pre>\n",
    "            </td>\n",
    "        </tr>\n",
    "        <tr>\n",
    "            <td><code>IndexError</code></td>\n",
    "            <td>Occurs when trying to access an index that is outside the bounds of a sequence (e.g., list, tuple).</td>\n",
    "            <td>\n",
    "                <pre><code>\n",
    "try:\n",
    "    my_list = [1, 2, 3]\n",
    "    value = my_list[4]  # Accessing an out-of-range index\n",
    "except IndexError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "                </code></pre>\n",
    "            </td>\n",
    "        </tr>\n",
    "    </table>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Q5. Explain ImportError. What is ModuleNotFoundError?</h3>\n",
    "<p><b>Answer.</b></p>\n",
    "  <h3>ImportError and ModuleNotFoundError in Python</h3>\n",
    "    \n",
    "<p>\n",
    "    The <code>ImportError</code> is a base class for exceptions that occur when an import statement fails. One specific subclass of <code>ImportError</code> is <code>ModuleNotFoundError</code>.\n",
    "    </p>\n",
    "\n",
    "<h3>ImportError:</h3>\n",
    "\n",
    "<p>\n",
    "        The <code>ImportError</code> is raised when an import statement cannot locate the specified module or when there are issues with the imported module.\n",
    "    </p>\n",
    "\n",
    "    <pre><code>\n",
    "try:\n",
    "    import non_existent_module  # Attempting to import a non-existent module\n",
    "except ImportError as e:\n",
    "    print(f\"ImportError: {e}\")\n",
    "    </code></pre>\n",
    "\n",
    "<p>\n",
    "        In this example, an attempt to import a module named <code>non_existent_module</code> results in an <code>ImportError</code> because the module does not exist.\n",
    "    </p>\n",
    "\n",
    "<h3>ModuleNotFoundError:</h3>\n",
    "\n",
    "<p>\n",
    "        <code>ModuleNotFoundError</code> is a specific subclass of <code>ImportError</code>. It is raised when the interpreter cannot locate the specified module during an import statement.\n",
    "    </p>\n",
    "\n",
    "<pre><code>\n",
    "try:\n",
    "    from non_existent_package import module_inside_package  # Importing a module from a non-existent package\n",
    "except ModuleNotFoundError as e:\n",
    "    print(f\"ModuleNotFoundError: {e}\")\n",
    "    </code></pre>\n",
    "\n",
    "<p>\n",
    "        In this example, an attempt to import a module from a non-existent package results in a <code>ModuleNotFoundError</code> because the specified package cannot be found.\n",
    "    </p>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Q6. List down some best practices for exception handling in python.</h3>\n",
    "\n",
    "<p><b>Answer.</b></p>\n",
    "\n",
    " <h3>Best Practices for Exception Handling in Python</h3>\n",
    "    \n",
    "<ol>\n",
    "        <li>\n",
    "            <strong>Use Specific Exception Types:</strong> Catch specific exceptions rather than using a broad <code>except</code> block. This helps in identifying and handling errors more precisely.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Avoid Bare Except:</strong> Avoid using a bare <code>except:</code> clause without specifying the exception type. It can make debugging difficult and catch unexpected errors.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Handle Exceptions Close to the Source:</strong> Place exception handling code close to where the exception occurs. This makes the code more readable and helps in understanding the context of the error.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Use <code>finally</code> for Cleanup:</strong> Utilize the <code>finally:</code> block for cleanup operations that should be executed regardless of whether an exception occurred or not.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Avoid Too Broad Exception Handling:</strong> Be cautious about catching exceptions that might hide bugs. Handle exceptions based on the specific errors you expect and can handle.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Log Exceptions:</strong> Use logging to record details about exceptions. It helps in debugging and monitoring application behavior.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Raise Exceptions Sparingly:</strong> Raise exceptions only when necessary. Use them to indicate exceptional conditions, not for normal program flow.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Use Custom Exceptions:</strong> Create custom exception classes for specific error conditions in your application. This makes error handling more meaningful.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Keep Exception Handling Simple:</strong> Keep exception-handling code simple and readable. Complex exception handling can make the code harder to maintain.\n",
    "        </li>\n",
    "        <li>\n",
    "            <strong>Test Exception Handling:</strong> Include tests for exception handling in your test suite. Ensure that the code responds correctly to expected exceptions.\n",
    "        </li>\n",
    "    </ol>"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
